[package]
name = "malware"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.26", features = ["derive"]}
windows = { version = "0.59.0", features = [
    "Win32_System_Threading",
]}