[package]
name = "shared_std"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133", default-features = false, features = ["alloc"] }
shared_no_std = { path = "../shared_no_std" }