[package]
name = "injected_dll"
version = "0.1.0"
edition = "2024"
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.59.0", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemServices",
] }